/**
 * build-content.mjs
 * Reads src/content/** and generates src/generated/content.generated.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { marked } from 'marked';

const ROOT = path.resolve(import.meta.dirname, '..');
const CONTENT_DIR = path.join(ROOT, 'src', 'content');
const OUTPUT_FILE = path.join(ROOT, 'src', 'generated', 'content.generated.ts');

// Configure marked
marked.setOptions({
  gfm: true,
  breaks: false,
});

// ── Posts ──────────────────────────────────────────────
const postsDir = path.join(CONTENT_DIR, 'posts');
const postFiles = fs.readdirSync(postsDir).filter((f) => f.endsWith('.md'));

const allPosts = postFiles
  .map((file) => {
    const raw = fs.readFileSync(path.join(postsDir, file), 'utf-8');
    const { data, content } = matter(raw);
    const contentHtml = marked.parse(content);
    const charCount = content.replace(/\s/g, '').length;
    const readingTime = Math.max(1, Math.ceil(charCount / 400));

    return {
      slug: data.slug ?? '',
      title: data.title ?? '',
      date: data.date ?? '',
      category: data.category ?? '',
      tags: data.tags ?? [],
      cover: data.cover ?? '',
      summary: data.summary ?? '',
      published: data.published !== false,
      contentHtml: typeof contentHtml === 'string' ? contentHtml : '',
      readingTime,
    };
  })
  .filter((p) => p.published)
  .sort((a, b) => b.date.localeCompare(a.date));

// Build prev/next links
const postsWithNav = allPosts.map((post, i) => ({
  ...post,
  prevSlug: i < allPosts.length - 1 ? allPosts[i + 1].slug : null,
  prevTitle: i < allPosts.length - 1 ? allPosts[i + 1].title : null,
  nextSlug: i > 0 ? allPosts[i - 1].slug : null,
  nextTitle: i > 0 ? allPosts[i - 1].title : null,
}));

// ── Projects ───────────────────────────────────────────
const projectsRaw = JSON.parse(
  fs.readFileSync(path.join(CONTENT_DIR, 'projects', 'projects.json'), 'utf-8'),
);

// Normalize projects — ensure all required fields exist
const projects = projectsRaw.map((p) => ({
  id: p.id || p.name || '',
  name: p.name || '',
  description: p.description || '',
  tags: p.tags || [],
  language: p.language || '',
  stars: p.stars ?? 0,
  forks: p.forks ?? 0,
  status: p.status || 'Building',
  cover: p.cover || '',
  github: p.github || '',
  demo: p.demo || '',
  featured: p.featured || false,
  archived: p.archived || false,
  fork: p.fork || false,
  updatedAt: p.updatedAt || new Date().toISOString(),
}));

// ── Profile ────────────────────────────────────────────
const profile = JSON.parse(fs.readFileSync(path.join(CONTENT_DIR, 'profile.json'), 'utf-8'));

// ── Site ───────────────────────────────────────────────
const site = JSON.parse(fs.readFileSync(path.join(CONTENT_DIR, 'site.json'), 'utf-8'));

// ── Gallery ────────────────────────────────────────────
const gallery = JSON.parse(fs.readFileSync(path.join(CONTENT_DIR, 'gallery.json'), 'utf-8'));

// ── i18n Translations ─────────────────────────────────
const i18nDir = path.join(CONTENT_DIR, 'i18n');
const i18nZhCN = JSON.parse(fs.readFileSync(path.join(i18nDir, 'zh-CN.json'), 'utf-8'));
const i18nEnUS = JSON.parse(fs.readFileSync(path.join(i18nDir, 'en-US.json'), 'utf-8'));

// ── AI Frontline ──────────────────────────────────────
const aiFrontlineNews = JSON.parse(
  fs.readFileSync(path.join(CONTENT_DIR, 'ai-frontline', 'news.json'), 'utf-8'),
);

const aiFrontlineSource = JSON.parse(
  fs.readFileSync(path.join(CONTENT_DIR, 'ai-frontline', 'source.json'), 'utf-8'),
);

// ── Lab AI Resources ─────────────────────────────────
const labAiTools = JSON.parse(
  fs.readFileSync(path.join(CONTENT_DIR, 'lab', 'ai-tools.json'), 'utf-8'),
);

const labAiProjects = JSON.parse(
  fs.readFileSync(path.join(CONTENT_DIR, 'lab', 'ai-projects.json'), 'utf-8'),
);

const labSources = JSON.parse(
  fs.readFileSync(path.join(CONTENT_DIR, 'lab', 'source.json'), 'utf-8'),
);

// ── Generate TypeScript ────────────────────────────────
const ts = `// Auto-generated by build-content.mjs — DO NOT EDIT
// Generated at: ${new Date().toISOString()}

export interface GeneratedPost {
  slug: string;
  title: string;
  date: string;
  category: string;
  tags: string[];
  cover: string;
  summary: string;
  published: boolean;
  contentHtml: string;
  readingTime: number;
  prevSlug: string | null;
  prevTitle: string | null;
  nextSlug: string | null;
  nextTitle: string | null;
}

export interface GeneratedProject {
  id: string;
  name: string;
  description: string;
  tags: string[];
  language: string;
  stars: number;
  forks: number;
  status: string;
  cover: string;
  github: string;
  demo: string;
  featured: boolean;
  archived: boolean;
  fork: boolean;
  updatedAt: string;
}

export interface GeneratedProfile {
  name: string;
  title: string;
  bio: string;
  avatar: string;
  github: string;
  email: string;
  interests: string[];
  skills: string[];
}

export interface GeneratedSite {
  siteName: string;
  description: string;
  defaultLanguage: string;
  nav: { labelKey: string; href: string }[];
  socialLinks: Record<string, string>;
}

export interface GeneratedGalleryItem {
  title: string;
  type: string;
  icon: string;
  bgColor: string;
}

export interface AiNewsItem {
  id: string;
  date: string;
  title: string;
  summary: string;
  source: string;
  url: string;
  category: 'model' | 'product' | 'funding' | 'opensource' | 'agent' | 'tool' | 'industry';
  tags: string[];
  fetchedAt: string;
}

export interface AiFrontlineSource {
  name: string;
  url: string;
  description: string;
  lastFetchedAt: string;
  contentStartDate: string;
  notice: string;
}

export interface LabResourceItem {
  id: string;
  title: string;
  summary: string;
  category: string;
  source: string;
  url: string;
  tags: string[];
  publishedAt: string;
  fetchedAt: string;
  date?: string;
}

export interface LabSource {
  key: string;
  name: string;
  url: string;
  targetFile?: string;
}

export interface LabSources {
  sources: LabSource[];
  lastFetchedAt: string;
  contentStartDate: string;
  notice: string;
}

export const POSTS: GeneratedPost[] = ${JSON.stringify(postsWithNav, null, 2)};

export const ALL_POSTS: GeneratedPost[] = ${JSON.stringify(
  allPosts.map((p) => ({ ...p, prevSlug: null, prevTitle: null, nextSlug: null, nextTitle: null })),
  null,
  2,
)};

export const PROJECTS: GeneratedProject[] = ${JSON.stringify(projects, null, 2)};

export const PROFILE: GeneratedProfile = ${JSON.stringify(profile, null, 2)};

export const SITE: GeneratedSite = ${JSON.stringify(site, null, 2)};

export const GALLERY: GeneratedGalleryItem[] = ${JSON.stringify(gallery, null, 2)};

export const AI_FRONTLINE_NEWS: AiNewsItem[] = ${JSON.stringify(aiFrontlineNews, null, 2)};

export const AI_FRONTLINE_SOURCE: AiFrontlineSource = ${JSON.stringify(aiFrontlineSource, null, 2)};

export const LAB_AI_TOOLS: LabResourceItem[] = ${JSON.stringify(labAiTools, null, 2)};

export const LAB_AI_PROJECTS: LabResourceItem[] = ${JSON.stringify(labAiProjects, null, 2)};

export const LAB_SOURCES: LabSources = ${JSON.stringify(labSources, null, 2)};

// ── i18n ───────────────────────────────────────────────
export type SupportedLocale = 'zh-CN' | 'en-US';

export const I18N_ZH_CN: Record<string, unknown> = ${JSON.stringify(i18nZhCN, null, 2)};

export const I18N_EN_US: Record<string, unknown> = ${JSON.stringify(i18nEnUS, null, 2)};

export const I18N_DICTIONARIES: Record<SupportedLocale, Record<string, unknown>> = {
  'zh-CN': I18N_ZH_CN,
  'en-US': I18N_EN_US,
};
`;

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, ts, 'utf-8');

console.log(
  `✅ content.generated.ts — ${allPosts.length} posts, ${projects.length} projects, ${gallery.length} gallery items, ${aiFrontlineNews.length} AI news, ${labAiTools.length} lab tools, ${labAiProjects.length} lab projects, i18n: zh=${Object.keys(i18nZhCN).length} namespaces`,
);
