/**
 * build-content.mjs
 * Reads src/content/** and generates src/generated/content.generated.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { marked } from 'marked';

const ROOT = path.resolve(import.meta.dirname, '..');
const CONTENT_DIR = path.join(ROOT, 'src', 'content');
const OUTPUT_FILE = path.join(ROOT, 'src', 'generated', 'content.generated.ts');

// Configure marked
marked.setOptions({
  gfm: true,
  breaks: false,
});

// ── Posts ──────────────────────────────────────────────
const postsDir = path.join(CONTENT_DIR, 'posts');
const postFiles = fs.readdirSync(postsDir).filter((f) => f.endsWith('.md'));

const allPosts = postFiles
  .map((file) => {
    const raw = fs.readFileSync(path.join(postsDir, file), 'utf-8');
    const { data, content } = matter(raw);
    const contentHtml = marked.parse(content);
    const charCount = content.replace(/\s/g, '').length;
    const readingTime = Math.max(1, Math.ceil(charCount / 400));

    return {
      slug: data.slug ?? '',
      title: data.title ?? '',
      date: data.date ?? '',
      category: data.category ?? '',
      tags: data.tags ?? [],
      cover: data.cover ?? '',
      summary: data.summary ?? '',
      published: data.published !== false,
      contentHtml: typeof contentHtml === 'string' ? contentHtml : '',
      readingTime,
    };
  })
  .filter((p) => p.published)
  .sort((a, b) => b.date.localeCompare(a.date));

// Build prev/next links
const postsWithNav = allPosts.map((post, i) => ({
  ...post,
  prevSlug: i < allPosts.length - 1 ? allPosts[i + 1].slug : null,
  prevTitle: i < allPosts.length - 1 ? allPosts[i + 1].title : null,
  nextSlug: i > 0 ? allPosts[i - 1].slug : null,
  nextTitle: i > 0 ? allPosts[i - 1].title : null,
}));

// ── Projects ───────────────────────────────────────────
const projects = JSON.parse(
  fs.readFileSync(path.join(CONTENT_DIR, 'projects', 'projects.json'), 'utf-8'),
);

// ── Profile ────────────────────────────────────────────
const profile = JSON.parse(
  fs.readFileSync(path.join(CONTENT_DIR, 'profile.json'), 'utf-8'),
);

// ── Site ───────────────────────────────────────────────
const site = JSON.parse(
  fs.readFileSync(path.join(CONTENT_DIR, 'site.json'), 'utf-8'),
);

// ── Gallery ────────────────────────────────────────────
const gallery = JSON.parse(
  fs.readFileSync(path.join(CONTENT_DIR, 'gallery.json'), 'utf-8'),
);

// ── Generate TypeScript ────────────────────────────────
const ts = `// Auto-generated by build-content.mjs — DO NOT EDIT
// Generated at: ${new Date().toISOString()}

export interface GeneratedPost {
  slug: string;
  title: string;
  date: string;
  category: string;
  tags: string[];
  cover: string;
  summary: string;
  published: boolean;
  contentHtml: string;
  readingTime: number;
  prevSlug: string | null;
  prevTitle: string | null;
  nextSlug: string | null;
  nextTitle: string | null;
}

export interface GeneratedProject {
  name: string;
  slug: string;
  description: string;
  tags: string[];
  status: string;
  cover: string;
  github: string;
  demo: string;
  featured: boolean;
  icon: string;
  accentColor: string;
  category: string;
}

export interface GeneratedProfile {
  name: string;
  title: string;
  bio: string;
  avatar: string;
  github: string;
  email: string;
  interests: string[];
  skills: string[];
}

export interface GeneratedSite {
  siteName: string;
  description: string;
  defaultLanguage: string;
  nav: { labelKey: string; href: string }[];
  socialLinks: Record<string, string>;
}

export interface GeneratedGalleryItem {
  title: string;
  type: string;
  icon: string;
  bgColor: string;
}

export const POSTS: GeneratedPost[] = ${JSON.stringify(postsWithNav, null, 2)};

export const ALL_POSTS: GeneratedPost[] = ${JSON.stringify(allPosts.map(p => ({ ...p, prevSlug: null, prevTitle: null, nextSlug: null, nextTitle: null })), null, 2)};

export const PROJECTS: GeneratedProject[] = ${JSON.stringify(projects, null, 2)};

export const PROFILE: GeneratedProfile = ${JSON.stringify(profile, null, 2)};

export const SITE: GeneratedSite = ${JSON.stringify(site, null, 2)};

export const GALLERY: GeneratedGalleryItem[] = ${JSON.stringify(gallery, null, 2)};
`;

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, ts, 'utf-8');

console.log(
  `✅ content.generated.ts — ${allPosts.length} posts, ${projects.length} projects, ${gallery.length} gallery items`,
);
